# Generated by Django 3.0.5 on 2021-12-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('mobile', models.CharField(blank=True, max_length=130, null=True, verbose_name='mobile')),
                ('gender', models.IntegerField(choices=[(0, 'male'), (1, 'female'), (2, 'not specified')])),
                ('address', models.CharField(blank=True, max_length=260, null=True, verbose_name='address')),
            ],
        ),
    ]
